version: '3.8'

networks:
  bp_network:
    driver: bridge

services:
  router:
    build:
      context: ./routing
    ports:
      - "2080:80"
    networks:
      - bp_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:7
    volumes:
      - ./db/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - bp_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "pass"

  bp_front:
    build:
      context: ./bp_front
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - bp_back
    networks:
      - bp_network

  bp_back:
    build:
      context: ./bp_back
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - bp_network
    environment:
      KTOR_MONGO_HOST: "mongo"
      KTOR_MONGO_PORT: "27017"
      KTOR_MONGO_DB_NAME: "bag_please"
      KTOR_MONGO_USER: "user"
      KTOR_MONGO_PASS: "pass"