import CssBaseline from "@mui/material/CssBaseline";
import type {Metadata, Viewport} from "next";
import {Inter} from "next/font/google";
import {ThemeProvider} from "@mui/material";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';
import theme from './theme'

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <AppRouterCacheProvider>
      <CssBaseline/>
      <ThemeProvider theme={theme}>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </AppRouterCacheProvider>
    </html>
  );
}
