GRAPHQL {{ws_host}}
Sec-Websocket-Protocol: graphql-transport-ws

subscription ItemUpdates {
    getItemUpdates {
        type
        item {
            id
            name
            checked
        }
    }
}