@id = {{$random.uuid}}
#@id = 90dd0772-bb63-439a-abd1-2fc3d59e5a69
@name = {{$random.alphabetic(10)}}

GRAPHQL {{host}}

mutation {
    saveItem(item: {id: "{{id}}", name: "{{name}}", checked: false}){
        id, name, checked
    }
}