ktor:
  development: false
  application:
    modules:
      - com.bagplease.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

db:
  mongo:
    host: "$KTOR_MONGO_HOST:localhost"
    port: "$KTOR_MONGO_PORT:27017"
    db_name: "$KTOR_MONGO_DB_NAME:bag_please"
    user: "$KTOR_MONGO_USER:user"
    pass: "$KTOR_MONGO_PASS:pass"
