ktor:
  development: false
  application:
    modules:
      - com.bagplease.ApplicationKt.module
  deployment:
    host: "0.0.0.0"
    port: 4000
    rootPath: "api"

jwt:
  secret: "$KTOR_JWT_SECRET:secret"
  issuer: "bag-please.com"
  audience: "bag-please.com"
  realm: "bag-please.com"
  admin_login: "$KTOR_ADMIN_LOGIN:admin"
  admin_pass: "$KTOR_ADMIN_PASS:admin"

db:
  mongo:
    host: "$KTOR_MONGO_HOST:localhost"
    port: "$KTOR_MONGO_PORT:27017"
    db_name: "$KTOR_MONGO_DB_NAME:bag_please"
    user: "$KTOR_MONGO_USER:user"
    pass: "$KTOR_MONGO_PASS:pass"