@id = {{$random.uuid}}
#@id = 72743544-31d4-428d-9d12-1b07d0dfb15d
@name = {{$random.alphabetic(10)}}
#@name = updated_name

GRAPHQL {{gql_host}}
Authorization: Bearer {{auth_token}}

mutation {
    saveCategory(category: {id: "{{id}}", name: "Grocery"}){
        id, name
    }
}